export const SET_CURRENT_SURVEY = 'SET_CURRENT_SURVEY';
export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';

export const FETCH_RESPONSE = 'FETCH_RESPONSE';
export const FETCH_RESPONSE_SUCCESS = 'FETCH_RESPONSE_SUCCESS';
export const FETCH_RESPONSE_FAILED = 'FETCH_RESPONSE_FAILED';
