import React from 'react';
import messages from './messages';

export default formatMessage => [
  {
    title: '#',
    dataIndex: 'orderNumber',
    key: 'orderNumber',
    align: 'center',
    width: 50,
    fixed: 'left',
    sorter: (a, b) => a.orderNumber < b.orderNumber,
  },
  {
    title: formatMessage(messages.nameLabel),
    dataIndex: 'content',
    key: 'content',
    editable: true,
    sorter: (a, b) => a.content.localeCompare(b.content),
  },
  {
    title: formatMessage(messages.stressLabel),
    dataIndex: 'content',
    key: 'content',
    editable: true,
    sorter: (a, b) => a.content.localeCompare(b.content),
  },
  {
    title: formatMessage(messages.worryLabel),
    dataIndex: 'content',
    key: 'content',
    editable: true,
    sorter: (a, b) => a.content.localeCompare(b.content),
  },
  {
    title: formatMessage(messages.depressionLabel),
    dataIndex: 'content',
    key: 'content',
    editable: true,
    sorter: (a, b) => a.content.localeCompare(b.content),
  },
  {
    title: formatMessage(messages.concentratingLabel),
    dataIndex: 'content',
    key: 'content',
    editable: true,
    sorter: (a, b) => a.content.localeCompare(b.content),
  },
  {
    title: formatMessage(messages.crazyLabel),
    dataIndex: 'content',
    key: 'content',
    editable: true,
    sorter: (a, b) => a.content.localeCompare(b.content),
  },
  {
    title: formatMessage(messages.socialInteractionLabel),
    dataIndex: 'content',
    key: 'content',
    editable: true,
    sorter: (a, b) => a.content.localeCompare(b.content),
  },
  {
    title: formatMessage(messages.studyLabel),
    dataIndex: 'content',
    key: 'content',
    editable: true,
    sorter: (a, b) => a.content.localeCompare(b.content),
  },
  {
    title: formatMessage(messages.workLabel),
    dataIndex: 'content',
    key: 'content',
    editable: true,
    sorter: (a, b) => a.content.localeCompare(b.content),
  },
  {
    title: formatMessage(messages.parentLabel),
    dataIndex: 'content',
    key: 'content',
    editable: true,
    sorter: (a, b) => a.content.localeCompare(b.content),
  },
  {
    title: formatMessage(messages.againstLabel),
    dataIndex: 'content',
    key: 'content',
    editable: true,
    sorter: (a, b) => a.content.localeCompare(b.content),
  },
  {
    title: formatMessage(messages.behaviorLabel),
    dataIndex: 'content',
    key: 'content',
    editable: true,
    sorter: (a, b) => a.content.localeCompare(b.content),
  },
  {
    title: formatMessage(messages.fightLabel),
    dataIndex: 'content',
    key: 'content',
    editable: true,
    sorter: (a, b) => a.content.localeCompare(b.content),
  },
];
